version: "3"
services:
  cbpmanager:
    #build: ./services/cbpmanager
    image: harbor.miracum.org/cbpmanager/cbpmanager:latest
    container_name: cbpmanager_container
    networks:
     - cbpmanager_net
    volumes:
      - "${STUDY_DIR:-../../study/}:/srv/shiny-server/study/"
      - "${LOG_DIR:-./cbpmanager/logs/}:/srv/shiny-server/logs/"
    command: ['Rscript', '-e', "cbpManager::cbpManager(studyDir = '/srv/shiny-server/study/', logDir = '/srv/shiny-server/logs/', host = '0.0.0.0', port = 3838)"]
  cbpmanager-shinyproxy:
    restart: unless-stopped
    #build: ./services/shinyproxy
    image: harbor.miracum.org/cbpmanager/cbpmanager-shinyproxy:latest
    container_name: cbpmanager_shinyproxy_container
    ports:
      - "${PORT:-8180}:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./shinyproxy-logs/server:/log"
      - "./shinyproxy-logs/container:/container-logs"
      - "./services/shinyproxy/application.yml:/app/application.yml"
    networks:
     - cbpmanager_net

networks:
  cbpmanager_net:
