name: Docker build (research)

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Build research containers
        run: FLAVOR=research docker compose build cbioportal
      - name: Build research cbioproxy
        run: FLAVOR=research docker compose build cbioproxy
