name: Docker build (research)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Build research containers
        run: FLAVOR=research docker compose build cbioportal
      - name: Build research cbioproxy
        run: FLAVOR=research docker compose build cbioproxy
