name: Release fhirspark

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: fhirspark Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/buschlab/fhirspark
          tags: |
            type=raw,enable=true,priority=200,prefix=,suffix=,value=
            type=raw,value=latest

      - name: fhirspark Build and push
        uses: docker/build-push-action@v2
        with:
          context: services/fhirspark
          platforms: linux/amd64,linux/arm
          push: true
          tags: ${{ steps.meta.outputs.tags }}