name: Docker build (mtb)

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Build mtb cBioPortal
        run: FLAVOR=mtb docker compose build cbioportal
      - name: Build mtb cbioproxy
        run: FLAVOR=mtb docker compose build cbioproxy
