name: Docker build (research)

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Build research containers
        run: FLAVOR=research docker compose build cbioportal
      - name: Build research cbioproxy
        run: FLAVOR=research docker compose build cbioproxy
