name: Docker build (mtb)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Build mtb cBioPortal
        run: FLAVOR=mtb docker compose build cbioportal
      - name: Build mtb cbioproxy
        run: FLAVOR=mtb docker compose build cbioproxy
